# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class CertRipper < Formula
  desc "Print, extract and validate TLS certificate chains for domains and URLs."
  homepage "https://github.com/recon-tools/cert-ripper-go"
  version "0.5.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/recon-tools/cert-ripper-go/releases/download/v0.5.6/cert-ripper-0.5.6-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "16cc0e78b755ac79bdcddce0d05aa331e8e26f8fa955e9894cc0002289ed793d"

      def install
        bin.install "bin/cert-ripper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/recon-tools/cert-ripper-go/releases/download/v0.5.6/cert-ripper-0.5.6-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7339c5ce2803d2481523b6b76a7d3f49d0922de53993a37e6c152b9243ad4d1c"

      def install
        bin.install "bin/cert-ripper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/recon-tools/cert-ripper-go/releases/download/v0.5.6/cert-ripper-0.5.6-linux-armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "2b4804c21479605fc1731b36e3193375d046d05635a37633ef9592d293252148"

      def install
        bin.install "bin/cert-ripper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/recon-tools/cert-ripper-go/releases/download/v0.5.6/cert-ripper-0.5.6-linux-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "e9202ad9c3bc94a3305ac95c034a693525a1a4d8c39aa4f63bb81315860ac00a"

      def install
        bin.install "bin/cert-ripper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/recon-tools/cert-ripper-go/releases/download/v0.5.6/cert-ripper-0.5.6-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "77a61f7f8e776835437f2c8756d663bba90efc631437d1047f66f1e95989bac2"

      def install
        bin.install "bin/cert-ripper"
      end
    end
  end

  test do
    system "#{bin}/cert-ripper", "--help"
  end
end
